# Generated by Django 3.2.5 on 2021-07-27 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(max_length=20)),
                ('latitude', models.FloatField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Looking',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mega.company')),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.company')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.company')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.company')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.company')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.rule')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mega.discount'),
        ),
    ]
