# Generated by Django 3.2.5 on 2021-08-06 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0003_auto_20210806_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='id_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date_cupon',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Период купона'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('Active', 'Активирован'), ('Expired', 'Просрочен'), ('Blocked', 'Заблонирован')], max_length=150),
        ),
    ]
