# Generated by Django 3.2.5 on 2021-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega', '0004_auto_20210806_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='order_num',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
